### ISSUE TITLE
在MAC IDEA上面编译运行源码报错

### ISSUE THREAD

**Issue by Seakeer** [mars-men/GsonFormatPlus#28]
JDK版本：java version "11.0.12" 2021-07-20 LTS
SDK版本：IntelliJ IDEA IU-203.6682.168 version 11.0.12
MAC版本：Catalina 10.15.4

查了好几个地方都没有找到解决方案，麻烦大佬们帮忙看下是什么问题，感谢。

```java
/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java -Xmx1024m -Xms256m -ea -Didea.config.path=/Users/seakeer/Library/Caches/JetBrains/IntelliJIdea2020.3/plugins-sandbox/config -Didea.system.path=/Users/seakeer/Library/Caches/JetBrains/IntelliJIdea2020.3/plugins-sandbox/system -Didea.plugins.path=/Users/seakeer/Library/Caches/JetBrains/IntelliJIdea2020.3/plugins-sandbox/plugins -Didea.classpath.index.enabled=false -Didea.required.plugins.id=com.your.company.unique.plugin.id -Didea.smooth.progress=false -Dapple.laf.useScreenMenuBar=true -Dapple.awt.fileDialogForDirectories=true "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=62291:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/openapi.jar:/Applications/IntelliJ IDEA.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea.jar" com.intellij.idea.Main
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method java.awt.EventQueue.dispatchEvent(java.awt.AWTEvent)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-09-17 11:07:31,367 [   2234]   WARN - i.mac.MacOSApplicationProvider - com/apple/eawt/OpenURIHandler 
java.lang.NoClassDefFoundError: com/apple/eawt/OpenURIHandler
	at com.intellij.ui.mac.MacOSApplicationProvider.initApplication(MacOSApplicationProvider.java:57)
	at com.intellij.idea.ApplicationLoader.startApp(ApplicationLoader.kt:152)
	at com.intellij.idea.ApplicationLoader.executeInitAppInEdt(ApplicationLoader.kt:68)
	at com.intellij.idea.ApplicationLoader.access$executeInitAppInEdt(ApplicationLoader.kt:1)
	at com.intellij.idea.ApplicationLoader$initApplication$1$1.run(ApplicationLoader.kt:374)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.OpenURIHandler
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:338)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 18 more
2021-09-17 11:07:33,080 [   3947]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: com.intellij] 
2021-09-17 11:07:33,090 [   3957]   WARN - tellij.ide.SystemHealthMonitor - issue detected: bundled.jre.version.message 
2021-09-17 11:12:53,385 [ 324252]   WARN - s.ui.configuration.SdkDetector - No version is returned for detected SDK IDEA JDK at /Applications/IntelliJ IDEA.app/Contents 
2021-09-17 11:13:09.862 java[6585:15928798] +[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x1138133b8
2021-09-17 11:13:09.864 java[6585:15928798] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x1138133b8'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3565dd07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6e3815bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff356dcbe7 __CFExceptionProem + 0
	3   CoreFoundation                      0x00007fff355c257b ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff355c1f58 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fff355d79cf __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007fff355d7963 ___CFXRegistrationPost1_block_invoke + 63
	7   CoreFoundation                      0x00007fff355d78d8 _CFXRegistrationPost1 + 372
	8   CoreFoundation                      0x00007fff355d7544 ___CFXNotificationPost_block_invoke + 80
	9   CoreFoundation                      0x00007fff355a76bd -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1554
	10  CoreFoundation                      0x00007fff355a6b69 _CFXNotificationPost + 1351
	11  Foundation                          0x00007fff37c1d866 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	12  AppKit                              0x00007fff32c3d44e __NSSelectedKeyboardInputSourcesChangedNotification + 58
	13  CoreFoundation                      0x00007fff355d79cf __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	14  CoreFoundation                      0x00007fff355d7963 ___CFXRegistrationPost1_block_invoke + 63
	15  libdispatch.dylib                   0x00007fff6f4ce6c4 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fff6f4cf658 _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fff6f4dacab _dispatch_main_queue_callback_4CF + 936
	18  CoreFoundation                      0x00007fff35621041 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	19  CoreFoundation                      0x00007fff355e0e47 __CFRunLoopRun + 2028
	20  CoreFoundation                      0x00007fff355dfffe CFRunLoopRunSpecific + 462
	21  HIToolbox                           0x00007fff34213abd RunCurrentEventLoopInMode + 292
	22  HIToolbox                           0x00007fff342137d5 ReceiveNextEventCommon + 584
	23  HIToolbox                           0x00007fff34213579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	24  AppKit                              0x00007fff3285ec99 _DPSNextEvent + 883
	25  AppKit                              0x00007fff3285d4e0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	26  libosxapp.dylib                     0x00000001131286fe -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	27  AppKit                              0x00007fff3284f1ee -[NSApplication run] + 658
	28  libosxapp.dylib                     0x0000000113128543 +[NSApplicationAWT runAWTLoopWithApp:] + 263
	29  libawt_lwawt.dylib                  0x00000001137dba38 +[AWTStarter starter:headless:] + 496
	30  libosxapp.dylib                     0x000000011312a059 +[ThreadUtilities invokeBlockCopy:] + 15
	31  Foundation                          0x00007fff37caf1bd __NSThreadPerformPerform + 204
	32  CoreFoundation                      0x00007fff355e1f12 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	33  CoreFoundation                      0x00007fff355e1eb1 __CFRunLoopDoSource0 + 103
	34  CoreFoundation                      0x00007fff355e1ccb __CFRunLoopDoSources0 + 209
	35  CoreFoundation                      0x00007fff355e09fa __CFRunLoopRun + 927
	36  CoreFoundation                      0x00007fff355dfffe CFRunLoopRunSpecific + 462
	37  libjli.dylib                        0x000000010b0845b5 CreateExecutionEnvironment + 398
	38  libjli.dylib                        0x000000010b08081f JLI_Launch + 1315
	39  java                                0x000000010b06f2cc main + 364
	40  libdyld.dylib                       0x00007fff6f528cc9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by junziqiao** [comment]
还真不知道，怎么办，我用的windows开发

**Comment by junziqiao** [comment]
应该是缺失依赖
