### ISSUE TITLE
使用报错 data err

### ISSUE THREAD

**Issue by zhugw** [mars-men/GsonFormatPlus#43]
非常简单的JSON也不能正常处理
```
{"age":30}
```
界面上提示`data  err!!`

idea.log中报错信息如下
```
2022-07-28 15:43:05,157 [1162679]   INFO - STDERR - java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "str" is null
2022-07-28 15:43:05,157 [1162679]   INFO - STDERR - 	at com.foxsteps.gsonformat.ConvertBridge.removeComment(ConvertBridge.java:288)
2022-07-28 15:43:05,157 [1162679]   INFO - STDERR - 	at com.foxsteps.gsonformat.ConvertBridge.collectDeclareFields(ConvertBridge.java:307)
2022-07-28 15:43:05,157 [1162679]   INFO - STDERR - 	at com.foxsteps.gsonformat.ConvertBridge.collectClassAttribute(ConvertBridge.java:235)
```
idea版本：
```
IntelliJ IDEA 2022.2 (Ultimate Edition)
Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
Metal Rendering is ON
Non-Bundled Plugins:
    GsonFormatPlus (1.6.1)
```

**Comment by z1143715275** [comment]
解决了吗

**Comment by pluginwad** [comment]
我也遇到了解决了吗？

**Comment by pluginwad** [comment]
> 解决了吗

试试把注解全都删掉留一个空类再转我的是这样解决的
